# filepath: /home/ardy/plant-disease/backend/docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=plant_disease_dev
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/plant_disease_dev
      - SECRET_KEY=development_secret_key
      - JWT_SECRET_KEY=jwt_secret_key_for_auth_tokens
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
      - ./uploads:/app/uploads  # Persist uploaded images
    networks:
      - app-network
    command: bash -c "python run.py"

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
